import {styled } from "@mui/material/styles";

export const  useStyles =
//  styled(
  {
  searchddInput: {
    color: "#212529",
    width: "240px",
    border: "1px solid #ced4da",
    height: "50px",
    display: "block",
    outline: "none",
    padding: "12px",
    fontSize: "1rem",
    fontWeight: "400",
    borderRadius: "8px",
    height: "38px",
    backgroundColor: "#fff",
    marginLeft: "80px",
  },
  formGroup: {
    marginBottom: "15px",
    width: "100%",
    marginTop: "10px !important",
  },
  formControlDisabled: {
    display: "block",
    height: "50px",
    width: "100%",
    padding: "12px",
    fontSize: "1rem",
    fontWeight: "400",
    color: "#212529",
    backgroundColor: "#eee",
    backgroundClip: "padding-box",
    border: "1px solid #ced4da",
    webkitAppearance: "none",
    mozAppearance: "none",
    appearance: "none",
    borderRadius: "0.25rem",
    outline: " none",
  },
  formControl: {
    display: "block",
    height: "50px",
    width: "100%",
    padding: "12px",
    fontSize: "1rem",
    fontWeight: "400",
    color: "#212529",
    backgroundColor: "#fff",
    backgroundClip: "padding-box",
    border: "1px solid #ced4da",
    webkitAppearance: "none",
    mozAppearance: "none",
    appearance: "none",
    borderRadius: "0.25rem",
    outline: " none",
    width:"100%"
  },
  textareaFormControl: {
    display: "block",
    outline: " none",
    width: "100%",
    padding: "12px",
    fontSize: "1.2rem",
    fontWeight: "400",
    resize: "none",
    color: "#212529",
    backgroundColor: "#fff",
    backgroundClip: "padding-box",
    border: "1px solid #ced4da",
    webkitAppearance: "none",
    mozAppearance: "none",
    appearance: "none",
    borderRadius: "0.25rem",
    fontFamily: "Public Sans,sans-serif",
  },
  formLabel: {
    marginBottom: "0.5rem",
    display: "inline-block",
    color: "grey",
    fontWeight: "bold",
    fontSize: "0.9rem",
  },
  formText: {
    marginTop: "0.25rem",
    fontSize: ".875em",
    color: "#6c757d",
  },

  formErrorStyle: {
    marginTop: "0.25rem",
    fontSize: ".875em",
    color: "red",
    display: "block",
    marginLeft: "0.5rem",
  },
  InnerText: {
    float: "right",
    marginTop: "0.25rem",
    fontSize: ".875em",
    color: "#6c757d",
  },
  formGroupSelect: {
    marginBottom: "15px",
    position: "relative",
  },
  DownArrow: {
    transform: "rotate(45deg)",
    "-webkit-transform": "rotate(45deg)",
    position: "absolute",
    top: "45px",
    right: "12px",
  },
  Arrow: {
    border: "solid #ced4d9",
    borderWidth: " 0 3px 3px 0",
    display: "inline-block",
    padding: " 3px",
  },
  dropdownWrapper: {
    position: "relative",
  },
  select_label: {
    color: "#a4b0be",
    fontWeight: "600",
    paddingLeft: "0.25rem",
    marginBottom: "-0.5rem",
  },
  dropDown: {
    borderRadius: "4px",
    boxShadow: "0 0 2px rgb(204, 204, 204)",
    backgroundColor: "#fff",
    maxHeight: "170px",
    overflow: "auto",
    listStyle: "none",
  },
  dropdownItem: {
    padding: "8px 12px",
    "&:hover": {
      backgroundColor: "rgb(0,171,85,.05)",
      color: "rgb(0,171,85)",
      cursor: "pointer",
      fontWeight: 600,
    },
  },
  menuWrapper: {
    position: "absolute",
    top: 100,
    width: "100%",
    zIndex: "50",
  },
  filename: {
    marginTop: "5px",
    marginLeft: "5px",
    color: "#aa9",
    fontSize: "14px",
  },
};
// );
